### ISSUE TITLE
Use Github Flavored Markdown for project descriptions

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3964] opened 2022-01-04 16:47 UTC
818d2673f20c1a87f235618cae242c129b49630f adds support for markdown on project descriptions but explicitly sets it to support original flavor rather than GitHub flavor. GitHub flavored markdown seems to be more widely supported these days and the use case for displaying markdown on GitHub and project descriptions is quite simmilar.  It also provides additional extensions that may be useful for project authors.

**Comment by jonrkarr** [comment] 2022-01-04 16:51
Duplicate of #3963

**Closed as completed by jonrkarr** 2022-01-04 16:51 UTC
