### ISSUE TITLE
Separate test for combine service to its own workflow

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3130] opened 2021-10-04 19:44 UTC
The test for the combine service can take a very long time. Nx considers any package updates to require testing all apps. Since the python app does not need to be tested as often we can create a separate workflow that is only run when needed.

**Comment by bilalshaikh42** [comment] 2021-10-05 22:38
It seems the tests actually timeout as well, so that will also need to be fixed

**Comment by jonrkarr** [comment] 2021-10-05 22:43
The tests shouldn't be particularly long. The Docker image building is longer.

**Comment by bilalshaikh42** [comment] 2021-10-05 23:34
I have seen a few times they run past 1hr and eventually timeout. The
latest run of the test on the dev  branch is an example

**Comment by jonrkarr** [comment] 2021-10-05 23:54
Which build are you referring to? I am aware of one issue with GillesPy2 sometimes never completing. I should really report that to them.

**Comment by bilalshaikh42** [comment] 2021-10-06 00:43
https://github.com/biosimulations/biosimulations/runs/3805127278
Timed out after 6hrs it seems

**Comment by jonrkarr** [comment] 2021-10-06 01:05
Its likely GillesPy2. I've seen this in my unit tests for GillesPy2 as well. The bug appeared in a relatively recent version.

Todo
- [ ] Use a different deterministic example simulation with GillesPy2
- [ ] Submit bug to GillesPy2
- [x] Use the [`timeout` argument](https://github.com/biosimulations/biosimulations/blob/18990f0ba317f18a3b747f2564e8ec83fe49a058/apps/combine-service/src/handlers/run/utils.py#L139) to cap the execution time of individual simulators or [pytest-timeout](https://pypi.org/project/pytest-timeout/)
- [x] Apply similar timeout to tests in biosimulators repos

Depending on the nature of the problem, a combination of a short timeout and retrying (e.g., with [flaky](https://github.com/box/flaky)) might be helpful.

**Comment by jonrkarr** [comment] 2021-10-06 04:25
In my hands, the tests take ~4 min. This is similar to the length in most builds. I'm having trouble replicating this, even with the same Docker image. Hopefully with the timeout, I can figure out which test is dragging in the GitHub action environment.

**Comment by jonrkarr** [comment] 2021-10-18 13:51
Closing because the last time out was two weeks ago on 2021-10-05 (https://github.com/biosimulations/biosimulations/actions/runs/1308317291). This can be re-opened if the issue re-appears.

If the COMBINE service is being tested unnecessarily frequently (when the service hasn't actually changed), an additional if statement could be attend to the CI workflow to skip testing the service when its unchanged.

**Closed as completed** 2021-10-18 13:52 UTC
Labels: future, CI/CD

**Comment by jonrkarr** [comment] 2021-10-25 14:08
The same problem re-occurred in the GillesPy2 tests this weekend. I added more verbose output to those tests to help figure out which algorithm is causing the problem. The issue is organized at biosimulators/Biosimulators_GillesPy2#15.

**Comment by bilalshaikh42** [comment] 2021-10-25 16:58
I have created a new cu workflow that utilizes the nx cloud and distributed
runners that is significantly faster. I am planning to switch over to it
once I work out a few remaining issues.

 We can use the existing ci workflow for just the python app if needed.

**Comment by jonrkarr** [comment] 2021-10-25 20:02
Sounds good. If it's just the python code left, the action could be simplified and run only when that subdirectory, Pipeline, or Dockerfile has changed.
