### ISSUE TITLE
Ontology update workflow caused builds to fail

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2031] opened 2021-01-25 15:35 UTC
The ontology update workflow led to builds failing.  Need to determine why and fix

**Comment by bilalshaikh42** [comment] 2021-01-25 16:37
https://github.com/biosimulations/Biosimulations/actions/runs/506630388

**Comment by jonrkarr** [comment] 2021-01-27 06:23
The error arises in this action: https://github.com/biosimulations/Biosimulations/runs/1755760527?check_suite_focus=true

It looks like the parsing of the KISAO owl file failed. The real issue is that this should have caused the workflow to fail (and commit no changed ontology files) rather to than commit an empty file.

It looks to me that the problem is with `tools/generate-ontologies`. In this script it sounds like errors with `java -jar ${script_dir}/GenerateOntology.jar ${ontology_url} ${temp_file}` aren't correctly being caught.

A couple possibilities
(a) Check the exit code of `java -jar ...` and make sure to exit when there's an error.
(b) After `java -jar ...` check that the JSON file for the ontology exists and isn't empty.

**Comment by jonrkarr** [comment] 2021-10-05 14:09
- [x] Can easily be fixed by adding `set -e` to the top of the script. This will force the script to stop on errors. In that case, the workflow would fail.
- [x] The same should be added to most shell scripts.

**Closed as completed** 2021-10-05 15:30 UTC
Labels: bug, released
