### ISSUE TITLE
Optional Data sharing in runBiosimulations

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1241] opened 2020-09-23 18:02 UTC
Add a select box to runBiosimulations to allow the simulation results to be used as a part of a dataset for simulation/reproducibility studies. 
Add a select box to runBiosimulations to allow the results to be publically available via a database

**Comment by jonrkarr** [comment] 2020-09-23 18:04
What is the purpose of the first point?

The second point could be addressed by a button to import a COMBINE archive into BioSimulations. However, this would be challenging to automate because this requires interpreting model files and supporting more of SED-ML.

**Comment by bilalshaikh42** [comment] 2020-09-23 22:25
I was thinking that a collection of simulation data might be interesting to Ion for example looking at  various simulators in terms of reproducibility/precision. It is also a general dataset that can perhaps be used for various machine learning/ statistical analyses. We can include the checkbox just so that if we later have some use for the data, it can be used

**Comment by jonrkarr** [comment] 2020-09-23 22:39
We would need to explain to users what the purpose is.

Alternatively, we could amend the terms of service to say (a) all submissions may be used to help improve the accuracy, precision, reproducibility, and consistency of simulation tools and (b) toward this end, they may be shared with the developers of simulation tools. The submissions would be used and shared in aggregate. This would enable us to use all data by requiring all users to opt-in to use the service. I see this as fairly similar to us collecting usage statistics to help us understand how many users use the service, from where, what simulators they use, etc for the purposes of improving the application.

@moraru, thoughts?

**Comment by jonrkarr** [comment] 2021-06-29 22:28
This will be folded into our new plan for populating the "platform".

1. User creates a simulation run (in RunBioSimulations)
2. User publishes this simulation run to the "platform" (BioSimulations)

Once published, the simulation can be used for any purpose permitted by its stated license, and a license statement (URL and human-readable description) will be required.

**Closed as completed by jonrkarr** 2021-06-29 22:28 UTC
Labels: enhancement, future, runBiosimulations
