### ISSUE TITLE
external links are broken in Simulator view

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1299] opened 2020-10-05 01:24 UTC
**Please describe the bug**
Some external links are broken on the simulator view page

 From the https://biosimulators.org/simulators/vcell/latest page: 

Working links
- [x] Kisao Link in parameter table -- mostly addressed; see below and #1313 
- [x] Kisao link in description
- [x] Framework link 
- [x] Format link
- [ ] Citation Link -- partly addressed; see below and #1311
- [x] Documentation link
- [x] More info link

**Comment by jonrkarr** [comment] 2020-10-13 22:48
The issue with the citation links is addressed in the UI. The problem is that the database doesn't conform to the expected data model outlined by the API. See #1311. Once the database is fixed, the UI will be fixed.

**Comment by jonrkarr** [comment] 2020-10-13 23:09
The KISAO links are mostly corrected. The rest need to be addressed by correcting the ids in the database to have the prefix `KISAO_`. See #1313.

**Comment by jonrkarr** [comment] 2020-10-15 23:00
The remaining issues are covered by #1311.

**Closed as completed by jonrkarr** 2020-10-15 23:00 UTC
Labels: bug, simulators
