### ISSUE TITLE
Recent changes break example simulations for runBioSimulations.dev

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1863] opened 2021-01-02 21:24 UTC
Attempting to view the example simulations:
https://github.com/biosimulations/Biosimulations/blob/dev/biosimulations/apps/dispatch/src/app/components/simulations/browse/example-simulations.json

Generates this error in run.biosimulations.dev.
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at t.setDataSets (view.component.ts:319)
    at h._next (view.component.ts:311)
    at h.__tryOrUnsub (Subscriber.js:183)
    at h.next (Subscriber.js:122)
    at c._next (Subscriber.js:72)
    at c.next (Subscriber.js:49)
    at o._next (map.js:35)
    at o.next (Subscriber.js:49)
    at o._next (map.js:35)
```

Note, this doesn't impact the deployed version at run.biosimulations.org.

It appears that the examples saved in the database are not compatible with the revised code. I'm guessing the data structure for results has changed. It sounds like either the code needs to be revised or the examples should be re-run (in which case `example-simulations.json` should be updated).

**Comment by bilalshaikh42** [comment] 2021-01-03 21:48
I don't remember making any changes to the dispatch code. I am able to run new simulations, and the api seems to be returning the data correctly.  However, for the example runs, the data is not being returned. There must be some issue with reading the files correctly on the HPC. 
Im pretty sure this is caused by the results files not being copied over to the dev environment properly. I can try to get them to copy over, but I am fairly sure this will work fine on the production environment

**Comment by bilalshaikh42** [comment] 2021-01-03 22:10
This was caused by an error in the exporting of the results data from the old database to the  dev database. This is now fixed, though some of the recent runs on the dev environment may not be found

**Closed as completed** 2021-01-03 22:11 UTC
Labels: bug
