### ISSUE TITLE
Some simulations fail for unclear reasons

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2083] opened 2021-01-30 08:10 UTC
Example failure
- 60151264b20a74247477037c (in dev)

Examples of simulations that remain in the processing state (all involve VCell 7.3.0.07, all in dev)
- 60151262b20a7469b4770370
- 60151264b20a746b8077037a
- 601513f0b20a741c067703a4
- 60151265b20a740fcd770382

**Comment by bilalshaikh42** [comment] 2021-01-30 15:04
This is caused by vcell not outputting the logs.yml. I forgot to account
for this. I'll put up a patch shortly.

**Comment by bilalshaikh42** [comment] 2021-02-01 19:55
Some interesting causes for this. 
The case with the vcell outputs has been resolved.
A  second issue has popped up causing the simulations to get stuck in the "processing" state. Sometimes, under high load, the dispatch api will not receive the update to set the status to "processing" until it has already received the update to set the status to "complete". Since the processing status arrives later, it sets the status to processing,and never receives a followup to change it back to complete. 
Once a complete/failed update has been received the api should reject further updates.

**Comment by bilalshaikh42** [comment] 2021-02-01 21:03
Simulation getting stuck in processing addressed in in  8b0a5ce1373af671b9733006c185f69db41b4996

**Comment by bilalshaikh42** [comment] 2021-02-01 21:06
Some simulations fail on submission under load. This seems to be a repeat of #1714

**Comment by bilalshaikh42** [comment] 2021-02-02 02:57
Simulations failing under load was caused by a parsing error that was not noticed until many simulations were submitted at once.
The queue system on the HPC almost immediately begins to run our jobs, unless there are a lot of jobs submitted at once. In that case, the job is queued and the status update needs to be parsed. There was a "\n" at the end of the output for queued jobs, causing the switch statement to fall to the default and miss the status. 

Some failures are still occuring due to ssh connection issues.

**Closed as completed by bilalshaikh42** 2021-02-02 02:57 UTC
Labels: bug
