### ISSUE TITLE
View simulation pages hit results and log endpoints multiple times due to chain of piping

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2417] opened 2021-04-11 20:28 UTC
I think rxjs `share` or `shareReplay` needs to be used to prevent the simulation pages (e.g., http://localhost:4200/simulations/60735544c94a8a93ae7bf2b5) from hitting the results and log endpoints multiple times.

I haven't read to figure out how this supposed to work. Instead, I tried blindly adding to no avail.

**Comment by bilalshaikh42** [comment] 2021-04-13 19:05
This was an interesting exercise actually. Notes as I was debugging that might be helpful sometime later:

If one loads the url as shown above, then logs are called multiple times. This is because the app as a whole is initializing, so the simulation stored in the cache is updated, triggering a refresh of all downstream observables. This can be fixed in the simulator service, but the interaction between my code (saving http requests) and yours (saving to/reading from local storage) is a bit unclear. 

However, if you click on the simulations from the table, you will see that the log endpoint is called just once like it should be. 

The results however is called multiple times. This is caused by the section of the view component that is not yet refactored to the chain method, so I don't think it is the chaining that is causing it.  Looking at the code that triggers the requests, it is caused by this subscription in the init method.

triggers: 
line 310,
line 343
line 469 in html -pipes the same observable as subscription in 310
line 310
line 310
line 301 in html   -pipes the same observable as subscription in 310
line 275


```    
const combineResultsSub = this.combineResultsStructure$.subscribe(
      (results: CombineResults | undefined): void => {
        if (results?.length) {
          this.setProjectOutputs(results);
        } else {
          this.snackBar.open(
            'Sorry! We were unable to get results for this simulation.',
            undefined,
            {
              duration: 5000,
              horizontalPosition: 'center',
              verticalPosition: 'bottom',
            },
          );
        }
      },
    );

```

Adding a share replay to the `combineResultsStructure$`  observable  eliminates most of the calls caused by the subscription at line 310. 
This leaves three calls, but all of them are caused by the same subscription.  The line causing this is is 
```        if (results?.length) {
          this.setProjectOutputs(results); 
```
Some logic within that function is causing the two extra calls. Tracing down to build2dviz() it contains the lines 

```
const combineResults = this.visualizationService.getCombineResults(
        this.uuid,
      );
      const combineResultsSub = combineResults.subscribe(  (combineResults: SedDatasetResultsMap | undefined): void => {
          if (combineResults) {
            this.combineResults = combineResults;
) ...
```  
So this is a new subscription that is created repeatedly based on the logic of the method. (I'm not clear if this is per report, or per variable).  We can move this observable to the top level of the component, essentially identically to the `combineResultsStructure$`   we created earlier. 

```
    this.combineResults$ = this.statusSuceeded$.pipe(
      map(
        (succeeded: boolean): Observable<SedDatasetResultsMap | undefined> =>
          succeeded
            ? this.visualizationService.getCombineResults(this.uuid)
            : of(undefined),
      ),
      concatAll(),
      shareReplay(1),
    );

``` 

Subscribing to this, rather than a newly created observable eliminates the last of the repeated calls. 

There is now 1 call to get the logs, 1 call to get the sparse result set and 1 call to get the full result set.

**Comment by jonrkarr** [comment] 2021-04-13 19:07
Great!

**Closed as completed** 2021-04-13 21:04 UTC
Labels: enhancement
