### ISSUE TITLE
Results retrieval fails for example simulation with VCell

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1790] opened 2020-12-20 00:19 UTC
The results retrieval fails with file not found error:
https://dispatch.biosimulations.dev/results/5fde96f8c5f1aa4f6dcce193?sparse=true

OMEX file: https://github.com/biosimulators/Biosimulators_test_suite/blob/dev/examples/sbml-core/Parmar-BMC-Syst-Biol-2017-iron-distribution.omex

**Comment by bilalshaikh42** [comment] 2020-12-20 07:52
This simulation seems to be the cause of the "Payload too large" errors that were showing up in the logs. 
This should be simple fix, assuming it is just the  config that is causing the issue.  There is also a 500 error being return by the api. I'm not able to tell from the logs if that is a separate issue, or somehow caused by the payload limit, but it shouldn't be, since that has a separate error code.  I will look into this

**Comment by jonrkarr** [comment] 2020-12-20 07:58
On my machine, the CSV file that VCell generates is only 166 kb

**Comment by jonrkarr** [comment] 2020-12-20 07:58
Thanks for looking into this.

**Comment by bilalshaikh42** [comment] 2020-12-20 08:08
I think https://github.com/biosimulations/Biosimulations/commit/4c0ec843c997d6cc43eb40f8da0a3d10bd20ee39 should have fixed it. We can check at run.biosimulations.dev once it deploys, and merge it into deploy branch if it works.

**Comment by bilalshaikh42** [comment] 2020-12-20 08:08
I think https://github.com/biosimulations/Biosimulations/commit/4c0ec843c997d6cc43eb40f8da0a3d10bd20ee39 should have fixed it. We can check at run.biosimulations.dev once it deploys, and merge it into deploy branch if it works.

**Comment by moraru** [comment] 2020-12-20 08:08
This is what it should look like on the file system where it is run.

[2020-12-20 03:04.53]  ~
[IonMoraru.phoenix] → ls -al /drives/c/tmp/biosim/CLI/simulation/*csv
-rwxrwx---    1 IonMorar UsersGrp     96295 Dec 20 03:03 /drives/c/tmp/biosim/CLI/simulation/tsk_0_0.csv
-rwxrwx---    1 IonMorar UsersGrp     96295 Dec 20 03:03 /drives/c/tmp/biosim/CLI/simulation/tsk_0_1.csv
-rwxrwx---    1 IonMorar UsersGrp     77847 Dec 20 03:03 /drives/c/tmp/biosim/CLI/simulation/tsk_0_2.csv
-rwxrwx---    1 IonMorar UsersGrp     77847 Dec 20 03:03 /drives/c/tmp/biosim/CLI/simulation/tsk_0_3.csv
-rwxrwx---    1 IonMorar UsersGrp     11586 Dec 20 03:03 /drives/c/tmp/biosim/CLI/simulation/tsk_1_0.csv
-rwxrwx---    1 IonMorar UsersGrp     11389 Dec 20 03:03 /drives/c/tmp/biosim/CLI/simulation/tsk_1_1.csv

**Comment by bilalshaikh42** [comment] 2020-12-20 08:12
I see only one file output as simulation_1.csv

**Comment by moraru** [comment] 2020-12-20 08:14
that may be a different test that I just ran - what uuid you looking at?

**Comment by bilalshaikh42** [comment] 2020-12-20 08:15
This is for the attached omex in this issue that Jonathan posted

**Comment by moraru** [comment] 2020-12-20 08:16
sorry, did not pay attention - i was referring to the issue i posted yesterday where only 4 of the 6 sims show up in the  viz selector

**Comment by moraru** [comment] 2020-12-20 08:16
that one was for vilar example

**Comment by bilalshaikh42** [comment] 2020-12-20 08:25
Ah i see. Can't find that issue now, but i remember reading it. That might be the same issue. The deployment on run.biosimulations.dev might have that fixed now.

**Comment by moraru** [comment] 2020-12-20 08:27
maybe, maybe not - there seems to be an issue with output not found that happens just for cvode; will describe in a new issue

**Comment by moraru** [comment] 2020-12-20 08:36
opened up #1796

**Closed as completed** 2020-12-20 08:38 UTC
